CREATE TABLE INCOME_INFO (
	DATE 		NUMBER(8)   NOT NULL,
	ODR			NUMBER(5)	NOT NULL,
	TYPE        NUMBER(1)   NOT NULL,
	ITEM		NUMBER(10) 	NOT NULL,
	PEOPLE	    NUMBER(10)  NOT NULL,
	PRICE		NUMBER(10)	NOT NULL
);

CREATE TABLE ITEM_INFO (
	TYPE        NUMBER(1) NOT NULL,
	CODE		NUMBER(10) NOT NULL,
	CATEGORY	VARCHAR(64) NOT NULL,
	NAME		VARCHAR(32) NOT NULL
);

INSERT INTO ITEM_INFO (CODE, TYPE, CATEGORY, NAME) VALUES (100101, 1, '일반계정 일반헌금', '십일조');
INSERT INTO ITEM_INFO (CODE, TYPE, CATEGORY, NAME) VALUES (100102, 1, '일반계정 일반헌금', '월정헌금');
INSERT INTO ITEM_INFO (CODE, TYPE, CATEGORY, NAME) VALUES (100103, 1, '일반계정 일반헌금', '주일헌금');
INSERT INTO ITEM_INFO (CODE, TYPE, CATEGORY, NAME) VALUES (100104, 1, '일반계정 일반헌금', '감사헌금');
INSERT INTO ITEM_INFO (CODE, TYPE, CATEGORY, NAME) VALUES (100105, 1, '일반계정 일반헌금', '기관한금');
INSERT INTO ITEM_INFO (CODE, TYPE, CATEGORY, NAME) VALUES (100106, 1, '일반계정 일반헌금', '목장헌금');
INSERT INTO ITEM_INFO (CODE, TYPE, CATEGORY, NAME) VALUES (100107, 1, '일반계정 일반헌금', '헌신예배헌금');
INSERT INTO ITEM_INFO (CODE, TYPE, CATEGORY, NAME) VALUES (100201, 1, '일반계정 절기헌금', '신년감사헌금');
INSERT INTO ITEM_INFO (CODE, TYPE, CATEGORY, NAME) VALUES (100202, 1, '일반계정 절기헌금', '부활감사헌금');
INSERT INTO ITEM_INFO (CODE, TYPE, CATEGORY, NAME) VALUES (100203, 1, '일반계정 절기헌금', '맥추감사헌금');
INSERT INTO ITEM_INFO (CODE, TYPE, CATEGORY, NAME) VALUES (100204, 1, '일반계정 절기헌금', '추수감사헌금');
INSERT INTO ITEM_INFO (CODE, TYPE, CATEGORY, NAME) VALUES (100205, 1, '일반계정 절기헌금', '성탄감사헌금');
INSERT INTO ITEM_INFO (CODE, TYPE, CATEGORY, NAME) VALUES (100301, 1, '일반계정 특별헌금', '기념헌금');
INSERT INTO ITEM_INFO (CODE, TYPE, CATEGORY, NAME) VALUES (100302, 1, '일반계정 특별헌금', '특별집회헌금');
INSERT INTO ITEM_INFO (CODE, TYPE, CATEGORY, NAME) VALUES (100303, 1, '일반계정 특별헌금', '선교헌금');
INSERT INTO ITEM_INFO (CODE, TYPE, CATEGORY, NAME) VALUES (100304, 1, '일반계정 특별헌금', '장애헌금');
INSERT INTO ITEM_INFO (CODE, TYPE, CATEGORY, NAME) VALUES (100305, 1, '일반계정 특별헌금', '북한선교헌금');
INSERT INTO ITEM_INFO (CODE, TYPE, CATEGORY, NAME) VALUES (100306, 1, '일반계정 특별헌금', '총회주일헌금');
INSERT INTO ITEM_INFO (CODE, TYPE, CATEGORY, NAME) VALUES (100307, 1, '일반계정 특별헌금', '여름사역특별헌금');
INSERT INTO ITEM_INFO (CODE, TYPE, CATEGORY, NAME) VALUES (100308, 1, '일반계정 특별헌금', '기타목적헌금');

INSERT INTO ITEM_INFO (CODE, TYPE, CATEGORY, NAME) VALUES (120101, 2, '비전센터건립금', '비전헌금');
INSERT INTO ITEM_INFO (CODE, TYPE, CATEGORY, NAME) VALUES (120102, 2, '비전센터건립금', '이자수입');
INSERT INTO ITEM_INFO (CODE, TYPE, CATEGORY, NAME) VALUES (120201, 2, '특별헌금', '기타목적(필리핀)');
INSERT INTO ITEM_INFO (CODE, TYPE, CATEGORY, NAME) VALUES (120202, 2, '특별헌금', '기타목적(장학회)');
COMMIT;

CREATE TABLE PEOPLE_INFO (
	CODE		NUMBER(10) PRIMARY KEY,
	NAME		VARCHAR(16) NOT NULL,
	GENDER		VARCHAR(4),
	AREA		VARCHAR(16),
	SECTION		VARCHAR(32),
	DUTY		VARCHAR(32),
	CONTACT		VARCHAR(16),
	AGE			NUMBER(3)
);

CREATE TABLE CUSTOM_PEOPLE_INFO (
	CODE		NUMBER(10) PRIMARY KEY,
	NAME		VARCHAR(16) NOT NULL,
	SECTION		VARCHAR(32),
	DUTY		VARCHAR(32)
);